services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: "postgresql_db"
    env_file:
      - path: ./.env
        required: true
    environment:
      POSTGRES_HOST: ${PG_HOST}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - ${PG_PORT}:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data